import { MenuItem } from './types';

export const MENU_ITEMS: MenuItem[] = [
  // 1. Espresso Base
  {
    id: 'c1',
    name: 'Espresso',
    note: '원두 선택 가능 (Full Moon, Crescent, New Moon)',
    price: 4500,
    category: 'coffee',
    imageUrl: '/images/menu/espresso.webp',
  },
  {
    id: 'c2',
    name: 'Americano',
    note: '원두 선택 가능 (Full Moon, Crescent, New Moon)',
    price: 5000,
    category: 'coffee',
    imageUrl: '/images/menu/americano.webp',
  },
  {
    id: 'c3',
    name: 'Cafe Latte',
    note: '부드러운 우유와 에스프레소',
    price: 5500,
    category: 'coffee',
    imageUrl: '/images/menu/cafe-latte.webp',
  },
  {
    id: 'c4',
    name: 'Cappuccino',
    note: '풍성한 거품의 조화',
    price: 5500,
    category: 'coffee',
    imageUrl: '/images/menu/cappuccino.webp',
  },
  {
    id: 'c5',
    name: 'Vanilla Bean Latte',
    note: '직접 만든 수제 시럽 사용',
    price: 6000,
    category: 'coffee',
    isBest: true,
    imageUrl: '/images/menu/vanilla-bean-latte.webp',
  },
  {
    id: 'c6',
    name: 'Cafe Mocha',
    note: '진한 초콜릿의 풍미',
    price: 6000,
    category: 'coffee',
    imageUrl: '/images/menu/cafe-mocha.webp',
  },
  {
    id: 'c7',
    name: 'Caramel Macchiato',
    note: '달콤한 카라멜 드리즐',
    price: 6000,
    category: 'coffee',
    imageUrl: '/images/menu/caramel-macchiato.webp',
  },

  // 2. Hand Drip & Cold Brew
  {
    id: 'c8',
    name: 'Lunaire Curation',
    note: '시즌별 싱글 오리진 (에티오피아, 콜롬비아 등)',
    price: 7000,
    category: 'coffee',
    imageUrl: '/images/menu/lunaire-curation.webp',
  },
  {
    id: 'c9',
    name: 'Cold Brew',
    note: '깔끔하고 깊은 맛, 대용량 가능',
    price: 5500,
    category: 'coffee',
    imageUrl: '/images/menu/cold-brew.webp',
  },

  // 3. Non-Coffee
  {
    id: 'nc1',
    name: 'Grapefruit Ade',
    note: '청량한 자몽 에이드',
    price: 6000,
    category: 'non-coffee',
    imageUrl: '/images/menu/grapefruit-ade.webp',
  },
  {
    id: 'nc2',
    name: 'Lemon Ade',
    note: '상큼한 레몬 에이드',
    price: 6000,
    category: 'non-coffee',
    imageUrl: '/images/menu/lemon-ade.webp',
  },
  {
    id: 'nc3',
    name: 'Starlight Ade',
    note: '수제 청에 식용 펄, 밤하늘 같은 비주얼',
    price: 6500,
    category: 'non-coffee',
    isNew: true,
    imageUrl: '/images/menu/starlight-ade.webp',
  },
  {
    id: 'nc4',
    name: 'Matcha Latte',
    note: '진한 제주산 말차',
    price: 6000,
    category: 'non-coffee',
    imageUrl: '/images/menu/matcha-latte.webp',
  },
  {
    id: 'nc5',
    name: 'Choco Velvet Latte',
    note: '다크 초콜릿의 깊은 풍미',
    price: 6000,
    category: 'non-coffee',
    imageUrl: '/images/menu/choco-velvet-latte.webp',
  },
  {
    id: 'nc6',
    name: 'Real Milk Tea',
    note: '냉침 방식으로 진하게 우린 홍차',
    price: 6000,
    category: 'non-coffee',
    imageUrl: '/images/menu/real-milk-tea.webp',
  },
  {
    id: 'nc7',
    name: 'Tea Selection',
    note: '잉글리시 브렉퍼스트, 얼그레이, 페퍼민트, 카모마일',
    price: 5500,
    category: 'non-coffee',
    imageUrl: '/images/menu/tea-selection.webp',
  },
  {
    id: 'nc8',
    name: 'Seasonal Fruit Juice',
    note: '신선한 계절 생과일',
    price: 7000,
    category: 'non-coffee',
    imageUrl: '/images/menu/seasonal-fruit-juice.webp',
  },

  // 4. Signatures (Top 3)
  {
    id: 'sig1',
    name: 'Lunaire Latte',
    note: '흑임자 베이스, 바닐라 크림, 달 모양 토핑',
    price: 6500,
    category: 'coffee',
    signature: true,
    imageUrl: '/images/menu/lunaire-latte.webp',
  },
  {
    id: 'sig2',
    name: 'Blue Moon Ade',
    note: '블루베리 & 레몬, 신비로운 새벽녘 색감',
    price: 6800,
    category: 'non-coffee',
    signature: true,
    imageUrl: '/images/menu/blue-moon-ade.webp',
  },
  {
    id: 'sig3',
    name: 'Midnight Einspanner',
    note: '콜드브루, 솔트 크림, 금가루 토핑',
    price: 6800,
    category: 'coffee',
    signature: true,
    imageUrl: '/images/menu/midnight-einspanner.webp',
  },

  // 5. Dessert (Fuel for Work)
  {
    id: 'd1',
    name: 'Financier',
    note: '고소한 버터 풍미 (클래식/초코)',
    price: 2800,
    category: 'dessert',
    imageUrl: '/images/menu/financier.webp',
  },
  {
    id: 'd2',
    name: 'Madeleine',
    note: '부드러운 식감 (레몬/얼그레이)',
    price: 2800,
    category: 'dessert',
    imageUrl: '/images/menu/madeleine.webp',
  },
  {
    id: 'd3',
    name: 'Lunaire Terrine',
    note: '꾸덕한 치즈/초코, 당 충전 메뉴',
    price: 5500,
    category: 'dessert',
    isBest: true,
    imageUrl: '/images/menu/lunaire-terrine.webp',
  },
  {
    id: 'd4',
    name: 'Croffle & Ice Cream',
    note: '바삭한 크로플과 바닐라 아이스크림',
    price: 8000,
    category: 'dessert',
    imageUrl: '/images/menu/croffle-and-ice-cream.webp',
  },
  {
    id: 'd5',
    name: 'Basque Cheese Cake',
    note: '진하고 부드러운 치즈 케이크',
    price: 7000,
    category: 'dessert',
    imageUrl: '/images/menu/basque-cheese-cake.webp',
  },
  {
    id: 'd6',
    name: 'Tiramisu',
    note: '마스카포네 치즈와 에스프레소',
    price: 7500,
    category: 'dessert',
    imageUrl: '/images/menu/tiramisu.webp',
  },
];
